import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import type { GeneralReportData, ManagementOverviewData, PartnersReportData, StockCardData, VehicleReportData, ZoneCostReportData } from "../types";
import { ReportsHub } from "./reports-hub";

beforeAll(() => { global.ResizeObserver = class { observe(){} unobserve(){} disconnect(){} } as unknown as typeof ResizeObserver; window.HTMLElement.prototype.scrollIntoView=vi.fn(); });
vi.mock("../actions",()=>({ getManagementOverviewAction:vi.fn(), getGeneralReportAction:vi.fn(), getZoneCostReportAction:vi.fn(), getVehicleReportAction:vi.fn(), getPartnersReportAction:vi.fn(), getStockCardAction:vi.fn(), getMetabaseDashboardAction:vi.fn() }));
import { getGeneralReportAction, getManagementOverviewAction, getPartnersReportAction, getStockCardAction, getVehicleReportAction, getZoneCostReportAction } from "../actions";

const general:GeneralReportData={totalInventoryValue:120000000,totalImportValue:50000000,totalIssuedCost:35000000,totalSalesRevenue:18000000,categoryBreakdown:[],defectsSummary:{totalDefects:2,repairedCount:1,repairCost:0,liquidationRevenue:0},fuelSummary:{totalImportedLiters:4000,totalDispensedLiters:3200,currentTankStock:1500,estimatedCost:64000000},stockLedger:[{variantId:"v1",productName:"Bóng đèn",variantLabel:"100W",unit:"bóng",categoryName:"Cơ điện",openingQty:40,inQty:60,outQty:20,closingQty:80,unitPrice:50000,closingValue:4000000}]};
const zones:ZoneCostReportData={grandTotalCost:30000000,zones:[{zoneId:"z1",zoneName:"Trại A",totalCost:30000000,percentage:100,issueCount:8,defectCount:1,items:[]}]};
const vehicles:VehicleReportData={totalLitersAllVehicles:450,vehicles:[{vehicleId:"x1",code:"XE-01",name:"Xe tải",plate:"60C-123.45",odoUnit:"km",fuelNorm:12,totalLiters:450,dispenseCount:6,totalUsageDiff:3800,avgRate:11.84,normDiff:-0.16,isOverNorm:false}]};
const partners:PartnersReportData={suppliers:[],customers:[]};
const stock:StockCardData={variantId:"v1",productName:"Bóng đèn",variantLabel:"100W",unit:"bóng",locationName:"Kho chính",openingStock:40,totalIn:60,totalOut:20,closingStock:80,entries:[]};
const overview:ManagementOverviewData={general,zones,vehicles,alerts:[{id:"a",severity:"warning",title:"Chi phí tập trung tại Trại A",description:"Chiếm 100%",value:"8 lượt cấp",targetSection:"operations",targetReport:"zones"}],generatedAt:"2026-09-20T08:00:00Z"};
const props={initialOverviewData:overview,initialGeneralData:general,locations:[{id:"loc-1",code:"KHO",name:"Kho chính"}],variants:[{id:"v1",productName:"Bóng đèn",variantLabel:"100W",unit:"bóng"}],initialDateRange:{from:"2026-09-01",to:"2026-09-30",preset:"this_month" as const}};

describe("ReportsHub three-section architecture",()=>{
 beforeEach(()=>{vi.clearAllMocks(); window.history.replaceState({},"","/reports"); vi.mocked(getManagementOverviewAction).mockResolvedValue(overview);vi.mocked(getGeneralReportAction).mockResolvedValue(general);vi.mocked(getZoneCostReportAction).mockResolvedValue(zones);vi.mocked(getVehicleReportAction).mockResolvedValue(vehicles);vi.mocked(getPartnersReportAction).mockResolvedValue(partners);vi.mocked(getStockCardAction).mockResolvedValue(stock);});
 it("renders management overview as the default section",()=>{render(<ReportsHub {...props}/>);expect(screen.getAllByRole("tab")).toHaveLength(3);expect(screen.getByRole("tab",{name:/Tổng quan quản trị/i}).getAttribute("aria-selected")).toBe("true");expect(screen.getByText("Tín hiệu cần chú ý")).toBeDefined();expect(screen.queryByRole("link",{name:/Xuất Excel/i})).toBeNull();});
 it("opens operational reports, loads detail data, and updates deep link",async()=>{render(<ReportsHub {...props}/>);fireEvent.click(screen.getByRole("tab",{name:/Báo cáo nghiệp vụ/i}));expect(window.location.search).toContain("section=operations");expect(screen.getByRole("link",{name:/Xuất Excel/i}).getAttribute("href")).toContain("type=stock_ledger");fireEvent.click(screen.getByRole("button",{name:/Chi phí theo trại/i}));await waitFor(()=>expect(getZoneCostReportAction).toHaveBeenCalledWith(expect.objectContaining({from:"2026-09-01",to:"2026-09-30"})));expect(window.location.search).toContain("report=zones");expect(screen.getByRole("link",{name:/Xuất Excel/i}).getAttribute("href")).toContain("type=zone_cost");});
 it("navigates from an alert to its detailed report",async()=>{render(<ReportsHub {...props}/>);fireEvent.click(screen.getByRole("button",{name:/Chi phí tập trung tại Trại A/i}));await waitFor(()=>expect(getZoneCostReportAction).toHaveBeenCalled());expect(screen.getByRole("heading",{name:"Chi phí theo trại"})).toBeDefined();});
 it("reloads overview for a changed period",async()=>{render(<ReportsHub {...props}/>);fireEvent.click(screen.getByRole("button",{name:"7 ngày qua"}));await waitFor(()=>expect(getManagementOverviewAction).toHaveBeenCalledWith(expect.objectContaining({preset:"7days"})));});
 it("restores section state on browser navigation",async()=>{render(<ReportsHub {...props}/>);await act(async()=>{window.history.pushState({},"","/reports?section=bi");window.dispatchEvent(new PopStateEvent("popstate"));});expect(screen.getByRole("tab",{name:/Phân tích chuyên sâu/i}).getAttribute("aria-selected")).toBe("true");});
});
