import type {
  BusinessEventKey,
  BusinessSubject,
  EventPolicy,
} from "./event-types";

export * from "./event-types";

export const BUSINESS_EVENT_KEYS: BusinessEventKey[] = [
  "requisition.submitted",
  "requisition.approved",
  "requisition.rejected",
  "requisition.fulfilled",
  "requisition.cancelled",
  "requisition.received",
  "requisition.returned",
  "receipt.created",
  "receipt.approved",
  "receipt.posted",
  "receipt.cancelled_or_reversed",
  "issue.created",
  "issue.sale_posted",
  "issue.internal_action_required",
  "issue.cancelled",
  "liquidation.created",
  "liquidation.approved",
  "liquidation.completed",
  "liquidation.rejected",
  "stocktake.created",
  "stocktake.posted_with_variance",
  "stocktake.posted_without_variance",
  "stocktake.completed_discrepancy",
  "stocktake.cancelled",
  "transfer.completed",
  "stock.adjusted",
  "assembly.completed",
  "disassembly.completed",
  "defect.created",
  "defect.resolution_selected",
  "defect.sent_to_liquidation",
  "repair.sent",
  "repair.ready_for_acceptance",
  "repair.accepted_and_returned",
  "repair.completed",
  "tool.borrowed",
  "tool.due_soon",
  "tool.overdue_started",
  "tool.returned",
  "tool.cancelled",
  "fuel.receipt_completed",
  "fuel.receipt_cancelled",
  "fuel.dispensed",
  "fuel.dispense_cancelled_or_adjusted",
  "exchange.created",
  "exchange.approved",
  "exchange.rejected",
  "exchange.issued",
  "exchange.received",
];

const POLICIES: Record<BusinessEventKey, EventPolicy<any>> = {
  // --- Requisition (Yêu cầu cấp phát vật tư) ---
  "requisition.submitted": {
    key: "requisition.submitted",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Chờ phê duyệt cấp phát vật tư`,
    getLink: (s) => `/requisitions/${s.id}`,
  },
  "requisition.approved": {
    key: "requisition.approved",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Đã được duyệt / Chuẩn bị xuất kho`,
    getLink: (s) => `/requisitions/${s.id}`,
  },
  "requisition.rejected": {
    key: "requisition.rejected",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Bị từ chối`,
    getLink: (s) => `/requisitions/${s.id}`,
  },
  "requisition.fulfilled": {
    key: "requisition.fulfilled",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Đã cấp phát / Sẵn sàng nhận`,
    getLink: (s) => `/requisitions/${s.id}`,
  },
  "requisition.cancelled": {
    key: "requisition.cancelled",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Đã hủy`,
    getLink: (s) => `/requisitions/${s.id}`,
  },
  "requisition.received": {
    key: "requisition.received",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Người yêu cầu đã nhận vật tư`,
    getLink: (s) => `/requisitions/${s.id}`,
  },
  "requisition.returned": {
    key: "requisition.returned",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Yêu cầu cấp phát] ${p.code} - Hoàn trả vật tư về kho`,
    getLink: (s) => `/requisitions/${s.id}`,
  },

  // --- Receipt & Orders (Phiếu đặt hàng / Nhập kho) ---
  "receipt.created": {
    key: "receipt.created",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đặt hàng / Nhập kho] ${p.code} - Tạo mới phiếu đặt hàng`,
    getLink: (s) => `/receipts/${s.id}`,
  },
  "receipt.approved": {
    key: "receipt.approved",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đặt hàng / Nhập kho] ${p.code} - Đã duyệt đơn đặt hàng / Chờ nhập kho`,
    getLink: (s) => `/receipts/${s.id}`,
  },
  "receipt.posted": {
    key: "receipt.posted",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Nhập kho] ${p.code} - Đã nhập kho thành công`,
    getLink: (s) => `/receipts/${s.id}`,
  },
  "receipt.cancelled_or_reversed": {
    key: "receipt.cancelled_or_reversed",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Nhập kho] ${p.code} - Đã hủy / Đảo bút toán nhập kho`,
    getLink: (s) => `/receipts/${s.id}`,
  },

  // --- Issue (Phiếu xuất kho) ---
  "issue.created": {
    key: "issue.created",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Xuất kho] ${p.code} - Tạo mới phiếu xuất kho`,
    getLink: (s) => `/issues/${s.id}`,
  },
  "issue.sale_posted": {
    key: "issue.sale_posted",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Xuất bán] ${p.code} - Đã hoàn tất xuất bán thương mại`,
    getLink: (s) => `/issues/${s.id}`,
  },
  "issue.internal_action_required": {
    key: "issue.internal_action_required",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Xuất kho] ${p.code} - Cần thực hiện xuất kho nội bộ`,
    getLink: (s) => `/issues/${s.id}`,
  },
  "issue.cancelled": {
    key: "issue.cancelled",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Xuất kho] ${p.code} - Đã hủy phiếu xuất kho`,
    getLink: (_s) => `/issues`,
  },

  // --- Liquidation (Thanh lý tài sản / vật tư) ---
  "liquidation.created": {
    key: "liquidation.created",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Thanh lý] ${p.code} - Đề xuất thanh lý vật tư mới cần duyệt`,
    getLink: (_s) => `/liquidations`,
  },
  "liquidation.approved": {
    key: "liquidation.approved",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Thanh lý] ${p.code} - Đã phê duyệt đề xuất thanh lý`,
    getLink: (_s) => `/liquidations`,
  },
  "liquidation.completed": {
    key: "liquidation.completed",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: ["creatorId"],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Thanh lý] ${p.code} - Đã hoàn tất thanh lý tài sản`,
    getLink: (_s) => `/liquidations`,
  },
  "liquidation.rejected": {
    key: "liquidation.rejected",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: ["creatorId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Thanh lý] ${p.code} - Từ chối phiếu thanh lý`,
    getLink: (_s: BusinessSubject) => `/liquidations`,
  },

  // --- Stocktake (Kiểm kê kho) ---
  "stocktake.created": {
    key: "stocktake.created",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Kiểm kê] ${p.code} - Khởi tạo kỳ kiểm kê kho`,
    getLink: (s) => `/stocktake/${s.id}`,
  },
  "stocktake.posted_with_variance": {
    key: "stocktake.posted_with_variance",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Kiểm kê] ${p.code} - Đã chốt kỳ kiểm kê (Có chênh lệch)`,
    getLink: (s) => `/stocktake/${s.id}`,
  },
  "stocktake.posted_without_variance": {
    key: "stocktake.posted_without_variance",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Kiểm kê] ${p.code} - Đã chốt kỳ kiểm kê khớp 100%`,
    getLink: (s) => `/stocktake/${s.id}`,
  },
  "stocktake.completed_discrepancy": {
    key: "stocktake.completed_discrepancy",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Kiểm kê] ${p.code} - Đã chốt kỳ kiểm kê (Có chênh lệch)`,
    getLink: (s: BusinessSubject) => `/stocktake/${s.id}`,
  },
  "stocktake.cancelled": {
    key: "stocktake.cancelled",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Kiểm kê] ${p.code} - Đã hủy kỳ kiểm kê kho`,
    getLink: (_s) => `/stocktake`,
  },

  // --- Transfer & Stock Adjustments (Điều chuyển kho & Điều chỉnh tồn) ---
  "transfer.completed": {
    key: "transfer.completed",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Chuyển kho] ${p.code || "DCK"} - Đã hoàn tất điều chuyển kho nội bộ`,
    getLink: (_s) => `/transfers`,
  },
  "stock.adjusted": {
    key: "stock.adjusted",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Điều chỉnh tồn] ${p.code || "ĐCK"} - Ghi nhận điều chỉnh tồn kho`,
    getLink: (_s) => `/transfers`,
  },

  // --- Assembly & Disassembly (Lắp ráp & Tháo dỡ) ---
  "assembly.completed": {
    key: "assembly.completed",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Lắp ráp] ${p.code || "LR"} - Hoàn tất lắp ráp bộ thành phẩm`,
    getLink: (_s) => `/assemblies`,
  },
  "disassembly.completed": {
    key: "disassembly.completed",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Tháo dỡ] ${p.code || "TD"} - Hoàn tất tháo dỡ bộ thành phẩm`,
    getLink: (_s) => `/assemblies`,
  },

  // --- Defect & Repair (Báo hỏng & Sửa chữa) ---
  "defect.created": {
    key: "defect.created",
    templateKind: "action",
    targetRoles: ["technician", "warehouse", "accountant"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Báo hỏng] ${p.code} - Thiết bị báo hỏng mới cần kiểm tra`,
    getLink: (_s) => `/defects`,
  },
  "defect.resolution_selected": {
    key: "defect.resolution_selected",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Báo hỏng] ${p.code} - Đã có phương án xử lý vật tư hỏng`,
    getLink: (_s) => `/defects`,
  },
  "defect.sent_to_liquidation": {
    key: "defect.sent_to_liquidation",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Báo hỏng] ${p.code} - Chuyển sang hàng đợi thanh lý`,
    getLink: (_s) => `/defects`,
  },
  "repair.sent": {
    key: "repair.sent",
    templateKind: "action",
    targetRoles: ["technician", "warehouse", "accountant"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Sửa chữa] ${p.code} - Thiết bị đã gửi đi sửa chữa`,
    getLink: (_s) => `/repairs`,
  },
  "repair.ready_for_acceptance": {
    key: "repair.ready_for_acceptance",
    templateKind: "action",
    targetRoles: ["technician", "warehouse", "accountant"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Sửa chữa] ${p.code} - Thiết bị đã sửa xong, chờ nghiệm thu`,
    getLink: (_s) => `/repairs`,
  },
  "repair.accepted_and_returned": {
    key: "repair.accepted_and_returned",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["reporterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Sửa chữa] ${p.code} - Thiết bị đã sửa xong và nhập lại kho`,
    getLink: (_s) => `/repairs`,
  },
  "repair.completed": {
    key: "repair.completed",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["creatorId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Sửa chữa] ${p.code} - Đã hoàn tất sửa chữa`,
    getLink: (_s: BusinessSubject) => `/repairs`,
  },

  // --- Tool Borrowing (Mượn - Trả dụng cụ) ---
  "tool.borrowed": {
    key: "tool.borrowed",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["borrowerId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Mượn dụng cụ] ${p.code} - Xác nhận bàn giao dụng cụ`,
    getLink: (_s) => `/tools`,
  },
  "tool.due_soon": {
    key: "tool.due_soon",
    templateKind: "action",
    targetRoles: [],
    targetParticipants: ["borrowerId"],
    excludeActor: false, // Automated system cron
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Nhắc hạn] ${p.code} - Dụng cụ sắp đến hạn hoàn trả (24h)`,
    getLink: (_s) => `/tools`,
  },
  "tool.overdue_started": {
    key: "tool.overdue_started",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["borrowerId"],
    excludeActor: false, // Automated system cron
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Cảnh báo] ${p.code} - Dụng cụ đã quá hạn hoàn trả`,
    getLink: (_s) => `/tools`,
  },
  "tool.returned": {
    key: "tool.returned",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["borrowerId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Trả dụng cụ] ${p.code} - Đã hoàn tất trả dụng cụ`,
    getLink: (_s) => `/tools`,
  },
  "tool.cancelled": {
    key: "tool.cancelled",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["borrowerId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Mượn dụng cụ] ${p.code} - Phiếu mượn đã bị hủy`,
    getLink: (_s) => `/tools`,
  },

  // --- Fuel (Nhiên liệu) ---
  "fuel.receipt_completed": {
    key: "fuel.receipt_completed",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Nhiên liệu] ${p.code} - Đã nhập kho nhiên liệu`,
    getLink: (_s) => `/fuel`,
  },
  "fuel.receipt_cancelled": {
    key: "fuel.receipt_cancelled",
    templateKind: "finance",
    targetRoles: ["warehouse", "accountant", "owner"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: true,
    getSubjectTitle: (p) => `[Nhiên liệu] ${p.code} - Đã hủy phiếu nhập nhiên liệu`,
    getLink: (_s) => `/fuel`,
  },
  "fuel.dispensed": {
    key: "fuel.dispensed",
    templateKind: "driver",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["driverId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Cấp dầu] ${p.code} - Xác nhận cấp phát nhiên liệu xe ${p.vehicleCode ?? ""}`,
    getLink: (_s) => `/fuel`,
  },
  "fuel.dispense_cancelled_or_adjusted": {
    key: "fuel.dispense_cancelled_or_adjusted",
    templateKind: "driver",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["driverId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Cấp dầu] ${p.code} - Hủy / Điều chỉnh cấp phát nhiên liệu`,
    getLink: (_s) => `/fuel`,
  },

  // --- Exchange (Đổi mới vật tư) ---
  "exchange.created": {
    key: "exchange.created",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: [],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đổi mới] ${p.code} - Chờ phê duyệt đổi mới`,
    getLink: (s: BusinessSubject) => `/defects/exchange/${s.id}`,
  },
  "exchange.approved": {
    key: "exchange.approved",
    templateKind: "action",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đổi mới] ${p.code} - Đã phê duyệt đổi mới`,
    getLink: (s: BusinessSubject) => `/defects/exchange/${s.id}`,
  },
  "exchange.rejected": {
    key: "exchange.rejected",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đổi mới] ${p.code} - Đã từ chối đổi mới`,
    getLink: (s: BusinessSubject) => `/defects/exchange/${s.id}`,
  },
  "exchange.issued": {
    key: "exchange.issued",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đổi mới] ${p.code} - Đã xuất kho vật tư mới`,
    getLink: (s: BusinessSubject) => `/defects/exchange/${s.id}`,
  },
  "exchange.received": {
    key: "exchange.received",
    templateKind: "result",
    targetRoles: ["warehouse", "accountant"],
    targetParticipants: ["requesterId"],
    excludeActor: true,
    allowsFinancialData: false,
    getSubjectTitle: (p) => `[Đổi mới] ${p.code} - Đã nhận vật tư đổi mới`,
    getLink: (s: BusinessSubject) => `/defects/exchange/${s.id}`,
  },
};

export function getEventPolicy<K extends BusinessEventKey>(key: K): EventPolicy<K> {
  const policy = POLICIES[key];
  if (!policy) {
    throw new Error(`Không tìm thấy policy cho business event key: ${key}`);
  }
  return policy;
}
